# Generated by Django 4.1.4 on 2022-12-20 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers_Model',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=100)),
                ('follower', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
